spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/comunity
    username: jun
    password: 2457
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug