spring:
  datasource:
    url: jdbc:h2:mem:dev
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        default_batch_fetch_size: 500
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

logging:
  level:
    org.hibernate.SQL: debug

server:
  error:
    whitelabel:
      enabled: false